# Generated by Django 3.2.4 on 2022-07-15 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0015_alter_cliente_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tope', models.DecimalField(decimal_places=2, default=100000, max_digits=12, verbose_name='Tope máximo de cuenta')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de apertura')),
                ('observaciones', models.CharField(max_length=100, null=True, verbose_name='Observaciones')),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cuenta Corriente',
                'verbose_name_plural': 'Cuentas Corrientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de movimiento')),
                ('tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1, verbose_name='Tipo de Movimiento')),
                ('observaciones', models.CharField(max_length=30, verbose_name='Observaciones')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentacorriente.cuentacorriente', verbose_name='Cuenta corriente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento cuenta corriente',
                'verbose_name_plural': 'Movimientos cuentas corrientes',
                'ordering': ['-id'],
            },
        ),
    ]
