# Generated by Django 3.2.4 on 2022-07-15 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0018_merge_0016_alter_ventaarticulo_id_0017_venta_cobrada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentacorriente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocuentacorriente',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.venta', verbose_name='Venta relacionada'),
        ),
        migrations.AlterField(
            model_name='movimientocuentacorriente',
            name='tipo',
            field=models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientocuentacorriente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.usuario', verbose_name='Usuario'),
        ),
    ]
