# Generated by Django 3.2.4 on 2022-07-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentacorriente', '0002_auto_20220715_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocuentacorriente',
            name='observaciones',
            field=models.TextField(max_length=30, null=True, verbose_name='Observaciones'),
        ),
    ]
