# Generated by Django 3.2.4 on 2022-04-19 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '__first__'),
        ('empleado', '__first__'),
        ('persona', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('caja_inicial', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('caja_final', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empleado.sucursal', verbose_name='Sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('cerrado', models.BooleanField(default=False)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.caja', verbose_name='Caja')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.sucursal', verbose_name='Sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='RetiroEfectivo',
            fields=[
                ('movimientocaja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caja.movimientocaja')),
                ('concepto', models.CharField(max_length=30, verbose_name='Concepto')),
            ],
            bases=('caja.movimientocaja',),
        ),
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_original', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Importe Original')),
                ('importe_cta_cte', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Importe Cuenta Corriente')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Saldo')),
                ('observaciones', models.CharField(max_length=30, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
                ('venta', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.venta', verbose_name='Venta')),
            ],
        ),
        migrations.CreateModel(
            name='Sueldo',
            fields=[
                ('movimientocaja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caja.movimientocaja')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.empleado', verbose_name='Empleado')),
            ],
            bases=('caja.movimientocaja',),
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('movimientocaja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caja.movimientocaja')),
                ('concepto', models.CharField(max_length=30, verbose_name='Concepto')),
                ('tipo_ingreso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.tipoingreso', verbose_name='Tipo de Ingreso')),
            ],
            bases=('caja.movimientocaja',),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('movimientocaja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caja.movimientocaja')),
                ('concepto', models.CharField(max_length=30, verbose_name='Concepto')),
                ('tipo_gasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.tipogasto', verbose_name='Tipo de Gasto')),
            ],
            bases=('caja.movimientocaja',),
        ),
        migrations.CreateModel(
            name='CobroVenta',
            fields=[
                ('movimientocaja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caja.movimientocaja')),
                ('venta', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.venta', verbose_name='Venta')),
            ],
            bases=('caja.movimientocaja',),
        ),
        migrations.CreateModel(
            name='CobranzaCtaCte',
            fields=[
                ('movimientocaja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caja.movimientocaja')),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Cuenta Corriente')),
                ('observaciones', models.CharField(max_length=30, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
            ],
            bases=('caja.movimientocaja',),
        ),
        migrations.CreateModel(
            name='Adelanto',
            fields=[
                ('movimientocaja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caja.movimientocaja')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.empleado', verbose_name='Empleado')),
            ],
            bases=('caja.movimientocaja',),
        ),
    ]
