# Generated by Django 3.1.3 on 2022-04-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_auto_20220421_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
