# Generated by Django 3.2.4 on 2022-04-30 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_auto_20220430_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=7, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Movieminto',
                'verbose_name_plural': 'Tipos de Movimiento',
            },
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='tipo_movimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caja.tipomovimiento', verbose_name='Tipo de Movimiento'),
            preserve_default=False,
        ),
    ]
