# Generated by Django 3.2.4 on 2022-05-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0011_empleado'),
        ('caja', '0011_auto_20220506_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adelanto',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado', verbose_name='Empleado'),
        ),
    ]
