# Generated by Django 3.2.4 on 2022-05-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0011_auto_20220504_2337'),
        ('caja', '0012_auto_20220506_2100'),
    ]

    operations = [
    ]
