# Generated by Django 3.2.4 on 2022-05-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0013_merge_0011_auto_20220504_2337_0012_auto_20220506_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adelanto',
            options={'ordering': ['-id'], 'verbose_name': 'Adelanto', 'verbose_name_plural': 'Adelantos'},
        ),
        migrations.AlterModelTable(
            name='adelanto',
            table='caja_movimientocaja_adelanto',
        ),
    ]
