# Generated by Django 3.2.4 on 2022-05-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0014_auto_20220509_1750'),
        ('caja', '0014_auto_20220512_2010'),
    ]

    operations = [
    ]
