# Generated by Django 3.2.4 on 2022-06-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0018_auto_20220521_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-id'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='cobranzactacte',
            options={'ordering': ['-id'], 'verbose_name': 'Cobranza Cuenta Corriente', 'verbose_name_plural': 'Cobranzas Cuenta Corriente'},
        ),
        migrations.AlterModelOptions(
            name='cobroventa',
            options={'ordering': ['-id'], 'verbose_name': 'Cobro de Venta', 'verbose_name_plural': 'Cobros de Venta'},
        ),
        migrations.AlterModelOptions(
            name='cuentacorriente',
            options={'ordering': ['-id'], 'verbose_name': 'Cuenta Corriente', 'verbose_name_plural': 'Cuentas Corrientes'},
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-id'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['-id'], 'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
        migrations.AlterModelOptions(
            name='movimientocaja',
            options={'ordering': ['-id'], 'verbose_name': 'Movimiento de Caja', 'verbose_name_plural': 'Movimientos de Caja'},
        ),
        migrations.AlterModelOptions(
            name='retiroefectivo',
            options={'ordering': ['-id'], 'verbose_name': 'Retiro de Efectivo', 'verbose_name_plural': 'Retiros de Efectivo'},
        ),
        migrations.AlterModelOptions(
            name='sueldo',
            options={'ordering': ['-id'], 'verbose_name': 'Sueldo', 'verbose_name_plural': 'Sueldos'},
        ),
        migrations.AlterModelOptions(
            name='tipogasto',
            options={'ordering': ['-id'], 'verbose_name': 'Tipo de Gasto', 'verbose_name_plural': 'Tipos de Gasto'},
        ),
        migrations.AlterModelOptions(
            name='tipoingreso',
            options={'ordering': ['-id'], 'verbose_name': 'Tipo de Ingreso', 'verbose_name_plural': 'Tipos de Ingreso'},
        ),
        migrations.AlterModelTable(
            name='cobranzactacte',
            table='caja_movimientocaja_cobranzactacte',
        ),
        migrations.AlterModelTable(
            name='cobroventa',
            table='caja_movimientocaja_cobroventa',
        ),
        migrations.AlterModelTable(
            name='gasto',
            table='caja_movimientocaja_gasto',
        ),
        migrations.AlterModelTable(
            name='ingreso',
            table='caja_movimientocaja_ingreso',
        ),
        migrations.AlterModelTable(
            name='retiroefectivo',
            table='caja_movimientocaja_retiroefectivo',
        ),
        migrations.AlterModelTable(
            name='sueldo',
            table='caja_movimientocaja_sueldo',
        ),
    ]
