# Generated by Django 3.2.4 on 2022-06-16 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0017_venta_cobrada'),
        ('cliente', '0013_alter_cliente_id'),
        ('caja', '0019_auto_20220615_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaDeCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Tarjeta de Credito')),
                ('banco', models.CharField(max_length=30, null=True, verbose_name='Banco Tarjeta')),
            ],
            options={
                'verbose_name': 'Tarjeta de Credito',
                'verbose_name_plural': 'Tarjetas de Credito',
                'db_table': 'tarjeta_de_credito',
            },
        ),
        migrations.CreateModel(
            name='PlanTarjetaDeCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=30, verbose_name='Nombre del Plan')),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Interes')),
                ('es_vale', models.BooleanField(default=False, verbose_name='Es Vale?')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.tarjetadecredito', verbose_name='Tarjeta de Credito')),
            ],
            options={
                'verbose_name': 'Plan Tarjeta de Credito',
                'verbose_name_plural': 'Planes Tarjetas de Credito',
                'db_table': 'plan_tarjeta_de_credito',
            },
        ),
        migrations.CreateModel(
            name='CuponPagoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe Pago')),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Recargo')),
                ('importe_con_recargo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe con Recargo')),
                ('numero_cupon', models.IntegerField(default=0, null=True, verbose_name='Numero de Cupon')),
                ('lote', models.CharField(max_length=10, null=True, verbose_name='Lote')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('observaciones', models.CharField(max_length=100, null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
                ('plan_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.plantarjetadecredito', verbose_name='Plan Tarjeta')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Cupon de Pago Tarjeta',
                'verbose_name_plural': 'Cupones de Pago Tarjetas',
                'ordering': ['-id'],
            },
        ),
    ]
