# Generated by Django 3.2.4 on 2022-06-17 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_alter_cliente_id'),
        ('venta', '0017_venta_cobrada'),
        ('caja', '0020_cuponpagotarjeta_plantarjetadecredito_tarjetadecredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponpagotarjeta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='cuponpagotarjeta',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.venta', verbose_name='Venta'),
        ),
    ]
