# Generated by Django 3.2.4 on 2022-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0021_auto_20220617_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponpagotarjeta',
            name='numero_tarjeta',
            field=models.IntegerField(default=0, max_length=4, null=True, verbose_name='Numero de Tarjeta'),
        ),
        migrations.AlterField(
            model_name='cuponpagotarjeta',
            name='lote',
            field=models.IntegerField(default=0, null=True, verbose_name='Lote'),
        ),
    ]
