# Generated by Django 3.2.4 on 2022-06-26 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0022_auto_20220622_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponpagotarjeta',
            name='numero_tarjeta',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Numero de Tarjeta'),
        ),
    ]
