# Generated by Django 3.2.4 on 2022-06-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0023_alter_cuponpagotarjeta_numero_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorriente',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cuponpagotarjeta',
            name='numero_tarjeta',
            field=models.IntegerField(default=0, null=True, verbose_name='Numero de Tarjeta'),
        ),
    ]
