# Generated by Django 3.2.4 on 2022-06-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0025_alter_cuentacorriente_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacorriente',
            name='importe_original',
        ),
    ]
