# Generated by Django 3.2.4 on 2022-06-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0026_remove_cuentacorriente_importe_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponpagotarjeta',
            name='lote',
            field=models.CharField(max_length=10, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='cuponpagotarjeta',
            name='numero_cupon',
            field=models.CharField(max_length=10, null=True, verbose_name='Numero de Cupon'),
        ),
        migrations.AlterField(
            model_name='cuponpagotarjeta',
            name='numero_tarjeta',
            field=models.CharField(max_length=10, null=True, verbose_name='Numero de Tarjeta'),
        ),
    ]
