# Generated by Django 3.2.4 on 2022-07-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0027_auto_20220627_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomovimiento',
            options={'verbose_name': 'Tipo de Movimiento', 'verbose_name_plural': 'Tipos de Movimiento'},
        ),
    ]
