# Generated by Django 3.2.4 on 2022-07-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0028_alter_tipomovimiento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacorriente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cuentacorriente',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='tipo_movimiento',
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='ingreso', max_length=7, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CobranzaCtaCte',
        ),
        migrations.DeleteModel(
            name='CuentaCorriente',
        ),
        migrations.DeleteModel(
            name='TipoMovimiento',
        ),
    ]
