# Generated by Django 3.2.4 on 2022-07-15 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0018_merge_0016_alter_ventaarticulo_id_0017_venta_cobrada'),
        ('caja', '0029_auto_20220715_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobroventa',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.venta', verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='tipogasto',
            name='descripcion',
            field=models.CharField(max_length=30, unique=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tipoingreso',
            name='descripcion',
            field=models.CharField(max_length=30, unique=True, verbose_name='Descripcion'),
        ),
    ]
