# Generated by Django 3.2.4 on 2023-07-24 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0023_rename_precio_ventaarticulo_total_articulo'),
        ('caja', '0031_alter_caja_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponpagotarjeta',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.venta', verbose_name='Venta'),
        ),
    ]
