# Generated by Django 3.2.4 on 2023-08-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0034_alter_plantarjetadecredito_nombre_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponpagotarjeta',
            name='numero_tarjeta',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Numero de Tarjeta'),
        ),
    ]
