# Generated by Django 3.2.4 on 2023-10-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_remove_cliente_fidelizado'),
        ('venta', '0025_alter_venta_empleado'),
        ('caja', '0035_alter_cuponpagotarjeta_numero_tarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido')),
                ('documento_identidad', models.CharField(max_length=12, verbose_name='Documento Identidad')),
                ('banco', models.CharField(blank=True, max_length=60, null=True, verbose_name='Banco')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago Con Tranferencia',
                'verbose_name_plural': 'Pagos Con Tranferencia',
                'ordering': ['-id'],
            },
        ),
    ]
