# Generated by Django 3.2.4 on 2023-10-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0036_pagotransferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagotransferencia',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe'),
        ),
    ]
