# Generated by Django 3.2.4 on 2023-10-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0037_pagotransferencia_importe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagotransferencia',
            name='cliente',
        ),
    ]
