# Generated by Django 3.2.4 on 2022-04-19 22:26

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Vacío especial', max_length=50, unique=True, verbose_name='Nombre')),
                ('abreviatura', models.CharField(help_text='Ejemplo: VACÍO ESP.', max_length=10, verbose_name='Abreviatura')),
                ('codigo', models.CharField(help_text='Ingrese el código de barras del artículo', max_length=10, verbose_name='Código de barras')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Vacío especial', max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoIva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Tipo de IVA',
                'verbose_name_plural': 'Tipos de IVA',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: gramo', max_length=50, unique=True, verbose_name='Nombre')),
                ('abreviatura', models.CharField(help_text='Ejemplo: gr', max_length=5, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo', verbose_name='Artículo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.listaprecio', verbose_name='Lista de Precios')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('nodo_padre', mptt.fields.TreeForeignKey(blank=True, help_text='Ejemplo: Carnes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodo_hijo', to='articulo.categoria', verbose_name='Categoría Padre')),
                ('tipo_iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.tipoiva', verbose_name='Tipo IVA')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.categoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.unidadmedida', verbose_name='Unidad de medida'),
        ),
    ]
