# Generated by Django 3.2.4 on 2022-05-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0009_auto_20220506_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codigo',
            field=models.CharField(help_text='Ingrese el código de barras del artículo', max_length=10, unique=True, verbose_name='Código de barras'),
        ),
    ]
