# Generated by Django 3.1.3 on 2022-05-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0009_auto_20220504_2337'),
        ('articulo', '0009_auto_20220506_2000'),
    ]

    operations = [
    ]
