# Generated by Django 3.2.4 on 2022-05-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0009_auto_20220504_2337'),
        ('articulo', '0010_alter_articulo_codigo'),
    ]

    operations = [
    ]
