# Generated by Django 3.2.4 on 2022-05-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0011_auto_20220509_1750'),
        ('articulo', '0011_merge_20220512_2007'),
    ]

    operations = [
    ]
