# Generated by Django 3.2.4 on 2022-05-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0010_merge_0009_auto_20220504_2337_0009_auto_20220506_2000'),
        ('articulo', '0012_merge_20220512_2016'),
    ]

    operations = [
    ]
