# Generated by Django 3.2.4 on 2022-05-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0014_auto_20220514_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprecio',
            name='nombre',
            field=models.CharField(help_text='Ejemplo: Clientes', max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddConstraint(
            model_name='precio',
            constraint=models.UniqueConstraint(fields=('articulo', 'sucursal', 'lista_precio'), name='unique_articulo_sucusal_lista'),
        ),
    ]
