# Generated by Django 3.2.4 on 2022-05-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0015_auto_20220517_2019'),
        ('articulo', '0015_auto_20220521_2020'),
    ]

    operations = [
    ]
