# Generated by Django 3.2.4 on 2022-05-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0015_auto_20220521_2020'),
        ('articulo', '0016_auto_20220521_2126'),
    ]

    operations = [
    ]
