# Generated by Django 3.2.4 on 2022-07-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0017_auto_20220526_1718'),
        ('articulo', '0017_merge_0015_auto_20220521_2020_0016_auto_20220521_2126'),
    ]

    operations = [
    ]
