# Generated by Django 3.2.4 on 2022-11-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0018_merge_20220713_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='Borrado?'),
        ),
    ]
