# Generated by Django 3.2.4 on 2022-11-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0019_articulo_borrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='borrado',
        ),
        migrations.AddField(
            model_name='articulo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
