# Generated by Django 3.2.4 on 2022-11-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0020_auto_20221109_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='is_deleted',
        ),
    ]
