# Generated by Django 3.2.4 on 2022-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0022_articulo_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='articulo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
