# Generated by Django 3.2.4 on 2022-11-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0023_auto_20221111_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
