# Generated by Django 3.2.4 on 2022-11-11 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0025_articulo_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='observaciones',
        ),
    ]
