# Generated by Django 3.2.4 on 2023-11-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulo', '0026_remove_articulo_observaciones'),
        ('empleado', '0016_merge_0015_auto_20220521_2126_0015_auto_20220526_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo', verbose_name='Articulo')),
            ],
            options={
                'verbose_name': 'Articulo Deposito',
                'verbose_name_plural': 'Articulos Deposito',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('domicilio', models.CharField(max_length=100, unique=True, verbose_name='Domicilio')),
            ],
            options={
                'verbose_name': 'Deposito',
                'verbose_name_plural': 'Depositos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('articulo_deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.articulodeposito', verbose_name='Articulo en Deposito')),
            ],
            options={
                'verbose_name': 'Movimiento de articulo',
                'verbose_name_plural': 'Movimientos de articulos',
            },
        ),
        migrations.CreateModel(
            name='ArticuloSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo', verbose_name='Articulo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Articulo Sucursal',
                'verbose_name_plural': 'Articulos Sucursal',
            },
        ),
        migrations.AddField(
            model_name='articulodeposito',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.deposito', verbose_name='Deposito'),
        ),
    ]
