# Generated by Django 3.2.4 on 2023-11-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoarticulo',
            name='articulo_deposito',
        ),
        migrations.AddField(
            model_name='movimientoarticulo',
            name='articulo',
            field=models.CharField(default='', max_length=100, verbose_name='Articulo'),
        ),
        migrations.AddField(
            model_name='movimientoarticulo',
            name='deposito',
            field=models.CharField(default='', max_length=100, verbose_name='Deposito'),
        ),
        migrations.AddField(
            model_name='movimientoarticulo',
            name='sucursal',
            field=models.CharField(default='', max_length=100, verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='movimientoarticulo',
            name='usuario',
            field=models.CharField(default='', max_length=50, verbose_name='Usuario'),
        ),
    ]
