# Generated by Django 3.2.4 on 2023-12-03 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0026_remove_articulo_observaciones'),
        ('stock', '0002_auto_20231129_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoarticulo',
            name='articulo_foraneo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo', verbose_name='Articulo'),
        ),
    ]
