# Generated by Django 3.2.4 on 2023-12-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_movimientoarticulo_articulo_foraneo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoarticulo',
            name='articulo_foraneo',
        ),
    ]
