# Generated by Django 3.2.4 on 2023-12-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_movimientostock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientostock',
            name='object_id_destino',
        ),
    ]
