# Generated by Django 3.2.4 on 2023-12-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stock', '0006_remove_movimientostock_object_id_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoarticulo',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='movimientoarticulo',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='object_id_origen',
        ),
        migrations.AddField(
            model_name='movimientoarticulo',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='movimientoarticulo',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
