# Generated by Django 3.2.4 on 2023-12-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20231219_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimientoStock',
        ),
    ]
