# Generated by Django 3.2.4 on 2023-12-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_delete_movimientostock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientoarticulo',
            old_name='content_type',
            new_name='lugar',
        ),
    ]
