# Generated by Django 3.2.4 on 2023-12-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_rename_content_type_movimientoarticulo_lugar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientoarticulo',
            old_name='object_id',
            new_name='lugar_object_id',
        ),
        migrations.RenameField(
            model_name='movimientoarticulo',
            old_name='lugar',
            new_name='lugar_type',
        ),
    ]
