# Generated by Django 3.2.4 on 2023-12-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20231229_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoarticulo',
            name='observaciones',
            field=models.CharField(default='', max_length=250, verbose_name='Observaciones'),
        ),
    ]
