# Generated by Django 3.2.4 on 2024-01-08 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stock', '0012_movimientoarticulo_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoarticulo',
            name='destino_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_destino', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='movimientoarticulo',
            name='origen_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to='contenttypes.contenttype'),
        ),
    ]
