# Generated by Django 3.2.4 on 2022-04-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='domicilio',
            field=models.CharField(max_length=100, unique=True, verbose_name='Domicilio'),
        ),
    ]
