# Generated by Django 3.1.3 on 2022-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_sucursal_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
