# Generated by Django 3.2.4 on 2022-04-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_auto_20220420_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
