# Generated by Django 3.2.4 on 2022-05-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0007_auto_20220502_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
