# Generated by Django 3.2.4 on 2022-07-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0015_auto_20220521_2126'),
        ('empleado', '0015_auto_20220526_1718'),
    ]

    operations = [
    ]
