# Generated by Django 3.1.3 on 2022-04-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20220420_0935'),
        ('usuario', '0002_auto_20220420_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='persona',
        ),
        migrations.AddField(
            model_name='usuario',
            name='empleado',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.empleado'),
        ),
    ]
