# Generated by Django 3.2.4 on 2022-05-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0011_empleado'),
        ('usuario', '0010_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado', verbose_name='Empleado'),
        ),
    ]
