# Generated by Django 3.2.4 on 2022-07-19 20:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0016_merge_0015_auto_20220521_2126_0015_auto_20220526_1718'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulo', '0018_merge_20220713_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInterno',
            fields=[
                ('numero_lote', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero de Lote')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo_movimiento_interno', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso'), ('Decomiso', 'Decomiso'), ('Transformacion Entrada', 'Transformacion Entrada'), ('Transformacion Salida', 'Transformacion Salida')], max_length=22, verbose_name='Tipo de Movimiento Interno')),
                ('abierto', models.BooleanField(default=True, verbose_name='Abierto')),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulado')),
                ('sucursal_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_destino', to='empleado.sucursal', verbose_name='Sucursal Destino')),
                ('sucursal_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_origen', to='empleado.sucursal', verbose_name='Sucursal Origen')),
                ('usuario_emisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_emisor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Emisor')),
                ('usuario_receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_receptor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Receptor')),
            ],
        ),
        migrations.CreateModel(
            name='TipoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInternoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_peso', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad / Peso')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Monto')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo', verbose_name='Articulo')),
                ('movimiento_interno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.movimientointerno', verbose_name='Movimiento Interno')),
            ],
            options={
                'verbose_name': 'Movimiento Interno Articulo',
                'verbose_name_plural': 'Movimiento Interno Articulos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('mes', models.CharField(choices=[('enero', 'Enero'), ('febrero', 'Febrero'), ('marzo', 'Marzo'), ('abril', 'Abril'), ('mayo', 'Mayo'), ('junio', 'Junio'), ('julio', 'Julio'), ('agosto', 'Agosto'), ('septiembre', 'Septiembre'), ('octubre', 'Octubre'), ('noviembre', 'Noviembre'), ('diciembre', 'Diciembre')], default='enero', max_length=10, verbose_name='Mes')),
                ('anio', models.IntegerField(default=2022, validators=[django.core.validators.MaxValueValidator(2040), django.core.validators.MinValueValidator(2020)])),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empleado.sucursal', verbose_name='Sucursal')),
                ('tipo_inventario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoinventario', verbose_name='Tipo de Inventario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Precio')),
                ('cantidad_peso', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad / Peso')),
                ('articulo_descripcion', models.CharField(max_length=50, verbose_name='Descripcion del articulo')),
                ('codigo', models.CharField(max_length=5, verbose_name='Codigo del articulo')),
                ('inventario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario', verbose_name='Inventario')),
            ],
        ),
    ]
