# Generated by Django 3.2.4 on 2022-07-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articuloinventario',
            options={'ordering': ['-id'], 'verbose_name': 'Articulo Inventario', 'verbose_name_plural': 'Articulos Inventario'},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-id'], 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterModelOptions(
            name='movimientointerno',
            options={'ordering': ['-numero_lote'], 'verbose_name': 'Movimiento Interno', 'verbose_name_plural': 'Movimientos Internos'},
        ),
        migrations.AlterModelOptions(
            name='tipoinventario',
            options={'ordering': ['-id'], 'verbose_name': 'Tipo de Inventario', 'verbose_name_plural': 'Tipos de Inventarios'},
        ),
        migrations.AddField(
            model_name='movimientointerno',
            name='principal',
            field=models.BooleanField(default=True),
        ),
    ]
