# Generated by Django 3.2.4 on 2022-07-20 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimientointernoarticulo_movimiento_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientointernoarticulo',
            name='movimiento_interno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.movimientointerno', verbose_name='Movimiento Interno'),
        ),
    ]
