# Generated by Django 3.2.4 on 2022-07-26 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20220725_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientointerno',
            name='movimiento_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.movimientointerno'),
        ),
    ]
