# Generated by Django 3.2.4 on 2022-07-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimientointernoarticulo_movimiento_interno'),
        ('inventario', '0004_alter_movimientointerno_movimiento_relacionado'),
    ]

    operations = [
    ]
