# Generated by Django 3.2.4 on 2022-08-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_movimientointerno_movimiento_relacionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientointerno',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
    ]
