# Generated by Django 3.2.4 on 2022-08-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_movimientointerno_fecha'),
        ('inventario', '0005_merge_20220728_0955'),
    ]

    operations = [
    ]
