# Generated by Django 3.2.4 on 2023-02-02 14:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0016_merge_0015_auto_20220521_2126_0015_auto_20220526_1718'),
        ('articulo', '0026_remove_articulo_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('valor', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Valor(%)')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField(default=False)),
                ('martes', models.BooleanField(default=False)),
                ('miercoles', models.BooleanField(default=False)),
                ('jueves', models.BooleanField(default=False)),
                ('viernes', models.BooleanField(default=False)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dia Semana',
                'verbose_name_plural': 'Dias de la Semana',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio de Promocion')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin de Promocion')),
                ('es_por_precio', models.BooleanField(default=False)),
                ('porcentaje_todos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('habilitada', models.BooleanField(default=False)),
                ('prioridad', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('observaciones', models.CharField(max_length=200, null=True, verbose_name='Observaciones')),
                ('dias_semana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promocion.diassemana', verbose_name='Dias de Promocion')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-id'],
                'unique_together': {('nombre', 'sucursal')},
            },
        ),
        migrations.CreateModel(
            name='PromocionArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo', verbose_name='Articulo Promocion')),
                ('promocion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promocion.promocion', verbose_name='Promocion')),
            ],
            options={
                'verbose_name': 'Promocion Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['-id'],
            },
        ),
    ]
