# Generated by Django 3.2.4 on 2023-06-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones'),
        ),
    ]
