# Generated by Django 3.2.4 on 2023-08-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0002_alter_promocion_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocionarticulo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
