# Generated by Django 3.2.4 on 2023-08-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0003_alter_promocionarticulo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocionarticulo',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promocion.promocion', verbose_name='Promocion'),
        ),
    ]
