# Generated by Django 3.2.4 on 2022-04-19 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreVentas',
            fields=[
                ('numero_cierre', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero de Cierre')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('ticket_desde', models.IntegerField(verbose_name='Ticket Desde')),
                ('ticket_hasta', models.IntegerField(verbose_name='Ticket Hasta')),
                ('ticket_cantidad', models.IntegerField(verbose_name='Ticket Cantidad')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe Cierre Ticket')),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='empleado.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'CierreVenta',
                'verbose_name_plural': 'Cierres de Ventas',
                'ordering': ['-numero_cierre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('numero_ticket', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero de Ticket')),
                ('fecha', models.DateField(verbose_name='Fecha de venta')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('anulado', models.BooleanField(default=False)),
                ('cliente', models.CharField(max_length=50, verbose_name='Nombre del Cliente')),
                ('dni_cliente', models.CharField(max_length=11, verbose_name='Dni de Cliente')),
                ('es_persona', models.BooleanField(default=True)),
                ('cierreventa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.cierreventas', verbose_name='Cierre de Venta')),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='empleado.sucursal', verbose_name='Sucursal')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-numero_ticket'],
            },
        ),
        migrations.CreateModel(
            name='VentaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_peso', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_promocion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nombre_articulo', models.CharField(max_length=30, verbose_name='Nombre de Articulo')),
                ('codigo_articulo', models.CharField(max_length=10, verbose_name='Codigo de Articulo')),
                ('venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'VentaArticulo',
                'verbose_name_plural': 'Ventas Articulos',
                'ordering': ['-id'],
            },
        ),
    ]
