# Generated by Django 3.2.4 on 2022-05-21 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0013_auto_20220514_0940'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venta', '0012_alter_ventaarticulo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
