# Generated by Django 3.2.4 on 2022-05-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0013_auto_20220521_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha de venta'),
        ),
    ]
