# Generated by Django 3.2.4 on 2022-05-22 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0013_auto_20220518_1848'),
        ('venta', '0013_auto_20220521_1255'),
    ]

    operations = [
    ]
