# Generated by Django 3.2.4 on 2022-05-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0014_alter_venta_fecha'),
        ('venta', '0015_alter_ventaarticulo_id'),
    ]

    operations = [
    ]
