# Generated by Django 3.2.4 on 2022-05-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0015_merge_0013_auto_20220517_2019_0014_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaarticulo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
