# Generated by Django 3.2.4 on 2022-06-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0016_merge_20220522_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cobrada',
            field=models.BooleanField(default=False),
        ),
    ]
