# Generated by Django 3.2.4 on 2022-07-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0016_alter_ventaarticulo_id'),
        ('venta', '0017_venta_cobrada'),
    ]

    operations = [
    ]
