# Generated by Django 3.2.4 on 2022-08-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0018_merge_0016_alter_ventaarticulo_id_0017_venta_cobrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierreventas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
