# Generated by Django 3.2.4 on 2022-08-10 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0016_merge_0015_auto_20220521_2126_0015_auto_20220526_1718'),
        ('venta', '0019_alter_cierreventas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierreventas',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.sucursal', verbose_name='Sucursal'),
        ),
    ]
