# Generated by Django 3.2.4 on 2023-01-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0022_alter_ventaarticulo_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventaarticulo',
            old_name='precio',
            new_name='total_articulo',
        ),
    ]
