# Generated by Django 3.2.4 on 2023-08-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0016_merge_0015_auto_20220521_2126_0015_auto_20220526_1718'),
        ('venta', '0024_venta_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado', verbose_name='Empleado'),
            preserve_default=False,
        ),
    ]
