# Generated by Django 3.2.4 on 2022-04-19 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('documento_identidad', models.CharField(max_length=12, unique=True, verbose_name='Documento Identidad')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('domicilio', models.CharField(max_length=100, verbose_name='Domicilio')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('cuil', models.CharField(max_length=12, unique=True, verbose_name='Cuil')),
                ('fecha_baja', models.DateField(default=False)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['-id'],
            },
            bases=('persona.persona',),
        ),
    ]
