# Generated by Django 3.2.4 on 2022-04-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_persona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, default=False, null=True),
        ),
    ]
