# Generated by Django 3.1.3 on 2022-04-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_empleado_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
