# Generated by Django 3.2.4 on 2022-05-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0012_auto_20220506_2100'),
        ('cliente', '0009_alter_cliente_id'),
        ('usuario', '0011_alter_usuario_empleado'),
        ('persona', '0010_alter_persona_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
