# Generated by Django 3.2.4 on 2022-07-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0014_auto_20220517_2019'),
        ('persona', '0015_alter_persona_id'),
    ]

    operations = [
    ]
