# Generated by Django 3.2.4 on 2023-08-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0017_alter_persona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domicilio'),
        ),
    ]
