# Generated by Django 3.2.4 on 2022-04-19 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '__first__'),
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion_iva', models.CharField(choices=[('ri', 'Responsable inscripto'), ('rn', 'Responsable no inscripto'), ('ex', 'Exento'), ('mo', 'Monotributo'), ('cf', 'Consumidor final')], max_length=30, verbose_name='Condición frente al IVA')),
                ('fecha_alta', models.DateField(auto_now=True)),
                ('fidelizado', models.BooleanField(default=False)),
                ('lista_precio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulo.listaprecio', verbose_name='Lista de Precios')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
    ]
