# Generated by Django 3.2.4 on 2022-07-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_auto_20220517_2019'),
        ('cliente', '0013_alter_cliente_id'),
    ]

    operations = [
    ]
