# Generated by Django 3.2.4 on 2023-06-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_alter_cliente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fidelizado',
        ),
    ]
